version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

    ports:
      - "${HOST_PORT}:6379"
      - "${HOST_PORT_UI}:8001"

    volumes:
      - "${DATA_DIR}:/data"
      - "${CONF_FILE}:/usr/local/etc/redis/redis.conf"

    environment:
      - TZ=Asia/Kolkata
