services:
  redis:
    image: redis/redis-stack:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    ports:
      - "${HOST_PORT}:6379"
      - "${HOST_PORT_UI}:8001"

    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}

    volumes:
      - "${DATA_DIR}:/data"
      - "${CONF_FILE}:/usr/local/etc/redis/redis.conf"

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
